name: dependent

on:
  repository_dispatch:
    types: update-event

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Respond to Event
        run: cd $GITHUB_WORKSPACE/.github/workflows && echo "hello, world."